SELECT COUNT(DISTINCT IFF(DER_9 > 0 AND DPI_1 > 0, DOCID, NULL)) AS READY_FOR_LOGISTICS
    ,COUNT(DISTINCT IFF(DER_9 > 0 AND DPI_n_1 > 0 AND DGI_n_9 > 0, DOCID, NULL)) AS IN_LOGISTICS
    ,COUNT(DISTINCT IFF( IS_COMPLETED > 0, DOCID, NULL)) AS BACKLOG_EWM
    ,COUNT(DISTINCT IFF( IS_SENT_TODAY > 0, DOCID, NULL)) AS SENT_TODAY
    ,COUNT(DISTINCT IFF( IS_CROSSDOCK_STARTER > 0, DOCID, NULL)) AS CROSSDOCK_STARTER
FROM (
    SELECT STATUS.DOCID
        ,SUM(IFF( STATUS_TYPE = 'DER' AND STATUS_VALUE =  '9', 1,0 )) AS DER_9
        ,SUM(IFF( STATUS_TYPE = 'DPI' AND STATUS_VALUE =  '1', 1,0 )) AS DPI_1
        ,SUM(IFF( STATUS_TYPE = 'DPI' AND STATUS_VALUE <> '1', 1,0 )) AS DPI_n_1
        ,SUM(IFF( STATUS_TYPE = 'DGI' AND STATUS_VALUE <> '9', 1,0 )) AS DGI_n_9
        ,SUM(IFF( STATUS_TYPE = 'DER' AND STATUS_VALUE =  '1', 1,0 )) AS IS_COMPLETED
        ,SUM(IFF( STATUS_TYPE = 'DGI' AND STATUS_VALUE =  '9' AND DATE_TRUNC('DAY',TS_TSTFR) = CURRENT_DATE() AND STATUS.DOCCAT = 'PDO', 1,0)) AS IS_SENT_TODAY
        ,SUM(IFF( STATUS_TYPE = 'DPI' AND STATUS_VALUE =  '1' AND PROCH."/CHCNL/CD_STARTER_FLAG" = 'X', 1, 0)) AS IS_CROSSDOCK_STARTER
    FROM ACCESS_DASH.WM4_DB_STATUS_DASH STATUS
    LEFT JOIN ACCESS_DASH.WM4_DB_PROCH_O_DASH PROCH ON PROCH.DOCID = STATUS.DOCID 
    GROUP BY STATUS.DOCID 
) 
	