SELECT COUNT(DISTINCT IFF(DER_9 > 0 AND DPI_1 > 0, DOCID, NULL)) AS IN_LOGISTICS
    ,COUNT(DISTINCT IFF( IS_COMPLETED > 0, DOCID, NULL)) AS BACKLOG_EWM
    ,COUNT(DISTINCT IFF( IS_SENT_TODAY > 0, DOCID, NULL)) AS SENT_TODAY
    ,COUNT(DISTINCT IFF( IS_CROSSDOCK_STARTER > 0, DOCID, NULL)) AS CROSSDOCK_STARTER
FROM (
    SELECT STATUS.DOCID
        ,SUM(IFF( (STATUS_TYPE = 'DER' AND STATUS_VALUE = '9'), 1,0 )) AS DER_9
        ,SUM(IFF( (STATUS_TYPE = 'DPI' AND STATUS_VALUE = '1'), 1,0 )) AS DPI_1
        ,SUM(IFF( STATUS_TYPE = 'DER' AND STATUS_VALUE = '1',1,0 )) AS IS_COMPLETED
        ,SUM(IFF( STATUS_TYPE = 'DGI' AND STATUS_VALUE = '9' AND DATE_TRUNC('DAY',TS_CRETST_WH) = CURRENT_DATE(), 1,0)) AS IS_SENT_TODAY
        ,SUM(IFF( STATUS_TYPE = 'DPI' AND STATUS_VALUE = '1' AND PROCH."/CHCNL/CD_STARTER_FLAG" = 'X', 1, 0)) AS IS_CROSSDOCK_STARTER
    FROM ACCESS_DASH.WM4_DB_STATUS_DASH STATUS
    JOIN ACCESS_DASH.WM4_DB_PROCH_O_DASH PROCH ON PROCH.DOCID = STATUS.DOCID 
    GROUP BY STATUS.DOCID 
) 