
-- LET'S TAKE IT FROM THE HEADER.
SELECT MAX(TO_TIMESTAMP(TO_CHAR(FLOOR(GLCHANGETIME)), 'yyyymmddhh24miss')) AS CHANGE
FROM ACCESS_DASH.ERP_ZGLUE_VBAK_DASH
WHERE 1 = 1;

-- SELECT MAX(TS_GLCHANGETIME) as CHANGE FROM ACCESS_DASH.ERP_ZGLUE_VBFA_DASH  WHERE 1=1