/*
 * HISTORY OF OPEN ORDERS - LAST 14 DAYS
 */

SELECT EOD_DT 
	,COUNT(1) AS OPEN_ORDERS
FROM ACCESS_DASH.P1_AVANTIS_OPEN_ORDERS_HIST_DASH
WHERE 1 = 1
	AND (OPEN_TOTAL + GODOT) > 0
GROUP BY 1
ORDER BY 1 DESC 
LIMIT 14;