/* OLD QUERY - WE WERE RECALCULATING OPEN ORDERS WITH NEW LOGIC ----------------------------------
 THIS WAS ADDRESSED ON THE P1 DATASETS
*/

-- SELECT IS_TODAY
-- 	,COUNT(DISTINCT VBELV) AS OPEN_ORDERS 	
-- 	,COUNT(DISTINCT IFF(BACKORDER > 0, VBELV, NULL)) AS BACKORDER
-- FROM (
-- 	SELECT VBFA.VBELV  AS VBELV
-- --		,IFF( DATE_TRUNC('DAY',VBAK.TS_CREATE_ERP) = CURRENT_DATE(), TRUE, FALSE ) AS IS_TODAY
-- 		,IFF( TO_DATE(VBAK.ERDAT,'YYYYMMDD') = CURRENT_DATE(), TRUE, FALSE ) AS IS_TODAY
-- 		,SUM(IFF(VBUK.WBSTK = 'C',1,0)) AS WBSTK
-- 		,SUM(IFF(VBAK.AUGRU = '',1,0)) AS AUGRU
-- 		,SUM(IFF(VKEK.PSTYV = 'YTA2' AND VKEK.BSTNR = '',1,0)) AS BACKORDER
-- 	FROM ACCESS_DASH.ERP_ZGLUE_VBAK_DASH VBAK
-- 	LEFT JOIN ACCESS_DASH.ERP_ZGLUE_VBFA_DASH VBFA ON VBAK.ORDER_ID = VBFA.VBELV
-- 	LEFT JOIN ACCESS_DASH.ERP_ZGLUE_VBUK_DASH VBUK ON VBFA.VBELN = VBUK.VBELN 
-- 	LEFT JOIN ACCESS_DASH.ERP_ZGLUE_CHCNL_VKEK_DASH VKEK ON VKEK.VBELN = VBFA.VBELV
-- 	WHERE 1 = 1
-- 		AND VBFA.VBTYP_N  = 'J'
-- 	GROUP BY VBFA.VBELV, IS_TODAY
-- )
-- WHERE (WBSTK=0 OR AUGRU=0)
-- GROUP BY IS_TODAY;



SELECT CASE TO_DATE(VBAK.ERDAT,'YYYYMMDD')
		WHEN CURRENT_DATE()    THEN 'Day 0'
		WHEN CURRENT_DATE() -1 THEN 'Day 1'
		WHEN CURRENT_DATE() -2 THEN 'Day 2'
		WHEN CURRENT_DATE() -3 THEN 'Day 3'
		WHEN CURRENT_DATE() -4 THEN 'Day 4'
		WHEN CURRENT_DATE() -5 THEN 'Day 5'
		WHEN CURRENT_DATE() -6 THEN 'Day 6'
	ELSE 'Older' END AS BACKLOG_DAY_CAT
	,COUNT(1) AS OPEN_ORDERS
FROM ACCESS_DASH.P1_AVANTIS_OPEN_DASH P1
JOIN ACCESS_DASH.ERP_ZGLUE_VBAK_DASH VBAK ON VBAK.ORDER_ID = P1.ORDER_ID 
WHERE 1 = 1
	AND (OPEN_TOTAL + GODOT) > 0
GROUP BY 1
ORDER BY 1 DESC;