

SELECT DATE_TRUNC('DAY',VBAK.TS_CREATE_ERP) AS CREATE_DATE
	,COUNT(DISTINCT VBFA.VBELV) AS OPEN_ORDERS_CREATED
FROM TABLEAU.ERP_ZGLUE_VBAK_TB VBAK
LEFT JOIN TABLEAU.ERP_ZGLUE_VBFA_TB VBFA ON VBAK.ORDER_ID = VBFA.VBELV
LEFT JOIN TABLEAU.ERP_ZGLUE_VBUK_TB VBUK ON VBFA.VBELN = VBUK.VBELN 
WHERE 1 = 1
	AND CREATE_DATE >= CURRENT_DATE()-1
	AND VBFA.VBTYP_N  = 'J'
	AND (VBUK.WBSTK <> 'C' OR VBAK.AUGRU <> '')
GROUP BY CREATE_DATE;