SELECT SEGMENT
	,DATE_EXTRACT
	,INCOME_STATEMENT
	,ACTUAL_MONTH
	,FORECAST_MONTH
	,BUDGET_MONTH
	,PREV_YEAR_MONTH
FROM DATAHUB.ACCESS_LAYER.VS_VIEW_EXTERNAL_REVENUE_V2  WHERE 1=1
UNION ALL
SELECT * 
	,NULL AS FORECAST_MONTH
	,NULL AS BUDGET_MONTH
	,NULL AS PREV_YEAR_MONTH
FROM (
	SELECT SEGMENT 
		,DATE_MONTH AS DATE_EXTRACT
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_OTC))           AS ACTIVE_CUSTOMER_OTC
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_RX))            AS ACTIVE_CUSTOMER_RX
		,TO_DOUBLE(SUM(CUSTOMER_NEW))                  AS CUSTOMER_NEW
		,TO_DOUBLE(SUM(CUSTOMER_REPEAT))               AS CUSTOMER_REPEAT
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER))               AS ACTIVE_CUSTOMER
		,TO_DOUBLE(SUM(CUSTOMER_NEW_OTC))              AS CUSTOMER_NEW_OTC
		,TO_DOUBLE(SUM(CUSTOMER_NEW_RX))               AS CUSTOMER_NEW_RX
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_NEW))           AS ORDERS_CUSTOMER_NEW
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_REPEAT))        AS ORDERS_CUSTOMER_REPEAT
		,TO_DOUBLE(SUM(ORDERS))                        AS ORDERS
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_OTC))           AS ORDERS_CUSTOMER_OTC
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_RX))            AS ORDERS_CUSTOMER_RX
		,TO_DOUBLE(SUM(NET_SALES))                     AS NET_SALES
		,TO_DOUBLE(SUM(NET_SALES_CUSTOMER_OTC))        AS NET_SALES_CUSTOMER_OTC
		,TO_DOUBLE(SUM(NET_SALES_CUSTOMER_RX))         AS NET_SALES_CUSTOMER_RX
		,TO_DOUBLE(SUM(SALES_NET_ONLINE))              AS SALES_NET_ONLINE
		,TO_DOUBLE(SUM(ORDERS_ONLINE))                 AS ORDERS_ONLINE
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_1Y_ROLLING))    AS ACTIVE_CUSTOMER_1Y_ROLLING
		,TO_DOUBLE(AVG(BASKET_AVG))                    AS BASKET_AVG
		,TO_DOUBLE(AVG(BASKET_AVG_OTC))                AS BASKET_AVG_OTC
		,TO_DOUBLE(AVG(BASKET_AVG_RX))                 AS BASKET_AVG_RX
		,TO_DOUBLE(AVG(NPS))                           AS NPS
		,TO_DOUBLE(SUM(SITE_VISITS))                   AS SITE_VISITS
		,TO_DOUBLE(AVG(ROAS))                          AS ROAS
		,TO_DOUBLE(SUM(ORDERS_1Y_ROLLING))             AS ORDERS_1Y_ROLLING
	FROM DATAHUB.ACCESS_LAYER.VS_VIEW_KPI_SEGMENT  
	WHERE 1=1
	GROUP BY SEGMENT ,DATE_MONTH
	UNION ALL 
	SELECT 'Group' AS SEGMENT 
		,DATE_MONTH AS DATE_EXTRACT
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_OTC))           AS ACTIVE_CUSTOMER_OTC
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_RX))            AS ACTIVE_CUSTOMER_RX
		,TO_DOUBLE(SUM(CUSTOMER_NEW))                  AS CUSTOMER_NEW
		,TO_DOUBLE(SUM(CUSTOMER_REPEAT))               AS CUSTOMER_REPEAT
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER))               AS ACTIVE_CUSTOMER
		,TO_DOUBLE(SUM(CUSTOMER_NEW_OTC))              AS CUSTOMER_NEW_OTC
		,TO_DOUBLE(SUM(CUSTOMER_NEW_RX))               AS CUSTOMER_NEW_RX
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_NEW))           AS ORDERS_CUSTOMER_NEW
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_REPEAT))        AS ORDERS_CUSTOMER_REPEAT
		,TO_DOUBLE(SUM(ORDERS))                        AS ORDERS
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_OTC))           AS ORDERS_CUSTOMER_OTC
		,TO_DOUBLE(SUM(ORDERS_CUSTOMER_RX))            AS ORDERS_CUSTOMER_RX
		,TO_DOUBLE(SUM(NET_SALES))                     AS NET_SALES
		,TO_DOUBLE(SUM(NET_SALES_CUSTOMER_OTC))        AS NET_SALES_CUSTOMER_OTC
		,TO_DOUBLE(SUM(NET_SALES_CUSTOMER_RX))         AS NET_SALES_CUSTOMER_RX
		,TO_DOUBLE(SUM(SALES_NET_ONLINE))              AS SALES_NET_ONLINE
		,TO_DOUBLE(SUM(ORDERS_ONLINE))                 AS ORDERS_ONLINE
		,TO_DOUBLE(SUM(ACTIVE_CUSTOMER_1Y_ROLLING))    AS ACTIVE_CUSTOMER_1Y_ROLLING
		,TO_DOUBLE(AVG(BASKET_AVG))                    AS BASKET_AVG
		,TO_DOUBLE(AVG(BASKET_AVG_OTC))                AS BASKET_AVG_OTC
		,TO_DOUBLE(AVG(BASKET_AVG_RX))                 AS BASKET_AVG_RX
		,TO_DOUBLE(AVG(NPS))                           AS NPS
		,TO_DOUBLE(SUM(SITE_VISITS))                   AS SITE_VISITS
		,TO_DOUBLE(AVG(ROAS))                          AS ROAS
		,TO_DOUBLE(SUM(ORDERS_1Y_ROLLING))             AS ORDERS_1Y_ROLLING
	FROM DATAHUB.ACCESS_LAYER.VS_VIEW_KPI_SEGMENT  
	WHERE 1=1
	GROUP BY DATE_MONTH 
)
UNPIVOT (ACTUAL_MONTH FOR INCOME_STATEMENT IN (ACTIVE_CUSTOMER_OTC,
												ACTIVE_CUSTOMER_RX,
												ACTIVE_CUSTOMER,
												CUSTOMER_NEW,
												CUSTOMER_REPEAT,
												CUSTOMER_NEW_OTC,
												CUSTOMER_NEW_RX,
												ORDERS_CUSTOMER_NEW,
												ORDERS_CUSTOMER_REPEAT,
												ORDERS,
												ORDERS_CUSTOMER_OTC,
												ORDERS_CUSTOMER_RX,
												NET_SALES,
												NET_SALES_CUSTOMER_OTC,
												NET_SALES_CUSTOMER_RX,
												SALES_NET_ONLINE,
												ORDERS_ONLINE,
												ACTIVE_CUSTOMER_1Y_ROLLING,
												BASKET_AVG,
												BASKET_AVG_OTC,
												BASKET_AVG_RX,
												NPS,
												SITE_VISITS,
												ROAS,
												ORDERS_1Y_ROLLING
												)
	)
;